# Generated by Django 3.2.1 on 2022-05-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email', models.EmailField(max_length=254, unique=True, verbose_name='Primary Email Address')),
                ('recovery_email', models.EmailField(max_length=254, verbose_name='Recovery Email Address')),
                ('preferences', models.CharField(choices=[('all', 'Receive all emails'), ('only', 'Only receive account related emails')], default='all', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.email')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
