# Generated by Django 3.2.1 on 2022-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220519_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_two_fac_auth_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
