# Generated by Django 3.2.1 on 2022-05-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_two_fac_auth_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
